# Site

defaults:
    -
     scope:
         path: ""
     values:
         author: "Helena Pikhartova"
         layout: post
         lang: en
         base-url: "/"
    -
     scope:
         path: cz
     values:
         lang: cz
         base-url: "/cz/"

# Value to use into url per language
langs-value:
    en: ""
    cz: cz

# Translation
t:
    home:
        en: "Home"
        cz: "Domů"
    title:
        en: "One Excited Positron"
        cz: "Jeden Veselý Pozitron"
    science:
        en: "Science"
        cz: "Věda"
    travel:
        en: "Travel"
        cz: "Cestování"
    tech:
        en: "Technology"
        cz: "Technika"
    about:
        en: "About"
        cz: "O mě"
    contact:
        en: "Contact"
        cz: "Kontakt"
    posts:
        en: "All Posts"
        cz: "Všechny Články"
    bio:
        en: "Hello :) Join me on the tour of the world and science!"
        cz: "Ahoj :) Vítejte na cestě po světě a vědě!"
    desc:
        en: "Thanks for stopping by to enjoy some fun facts about science especially physics and escpecially especially (especially^2) accelerator physics, I also write about tech and travel!"
        cz: "Díky že jste se stavili, můžete si přečíst něco z vědy, konkrétně fyziky a konkrétně konkrétně něco o mých oblíbených urychlovačích, taky nechybí technika a cestování!"



reading_time:       false
words_per_minute:   200
logo:               'assets/img/logo.jpg'
background:         'assets/img/intro.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://excitedpositron.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed


# Comments
disqus_shortname:   excitedpositron-github-io

# Social
google:
  analytics:		UA-115436794-1
email:			helena.pikhartova@gmail.com
twitter:            	ExcitedPositron
#github-url:		ExcitedPositron
linkedin:	    	helena-pikhartova-b1b29a91	
#instagram:          	username

# Gems
plugins_dir: [
  "jekyll-mentions",
  "jekyll-feed",
  "jekyll-sitemap",
#  "jekyll-gist",
  "jekyll-i18n"
]

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]

timezone: Europe/Geneva
