# Site
title:
  en: One Excited Positron
  cz: Jeden Veselý Pozitron
t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/"
    
  cz:
    home:
      name: "Domů"
      url: "/"
    about:
      name: "O me"
      url: "//"
bio:
  en: Hello :) Join me on the tour of the world and science!
  cz: Ahoj :) Vítejte na cestě po světě a vědě!

description:
  en: Thanks for stopping by to enjoy some fun facts about science especially physics and escpecially especially (especially^2) accelerator physics!
  cz: Díky že jste se stavili, můžete si přečíst něco z vědy, konkrétně fyziky a konkrétně konkrétně něco o mých oblíbených urychlovačích!
index:
  en: index.html
  cz: uvod.html
reading_time:       false
words_per_minute:   200
logo:               'assets/img/logo.jpg'
background:         'assets/img/intro.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://excitedpositron.github.io


# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed


# Comments
disqus_shortname:   excitedpositron-github-io

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:	    UA-115436794-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:			helena.pikhartova@gmail.com
twitter:            	ExcitedPositron
github-url:		ExcitedPositron
linkedin:	    	helena-pikhartova-b1b29a91	
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist


jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
